#!/usr/bin/env bash

source setup_lib.bash

CONFIG_DIR="$HOME/.config"

main() {
  printf "Hello Ben. Let's sync your dotfiles :)\n\n"
  symlinking_config_files
  check_third_party_tools
}

symlinking_config_files() {
  printf "symlinking config files...\n"

  # VIM
  dotfile_link "vim/.vim" "$HOME/.vim"

  # ZSH
  dotfile_link "zsh/.zshenv_wrapper" "$HOME/.zshenv"
  dotfile_link "zsh/.zshenv" "$CONFIG_DIR/zsh/.zshenv"
  dotfile_link "zsh/.zshrc" "$CONFIG_DIR/zsh/.zshrc"

  # LF
  dotfile_link "lf/lfrc" "$CONFIG_DIR/lf/lfrc"

  # CTAGS
  dotfile_link "ctags" "$HOME/.ctags.d"

  printf "symlinking complete!\n\n"
}

# TODO create a function for installing things from git
# TODO create a function for installing missing things from brew

check_third_party_tools() {
  printf "checking third party tools...\n"
  printf "third party tool check complete!\n\n"
}

main
