#!/bin/sh
echo "hello..."
echo "get ready for jazz!"

is_not_symlink()
{
  FILE=$1
  if [ -f $FILE -a ! -L $FILE ]; then
    return 0
  else
    return $?
  fi
}

if is_not_symlink $HOME/.vimrc || is_not_symlink $HOME/.zshrc; then
  if [ ! -d $HOME/.olddotfiles ]; then
    echo "We need a place for old dot files - creating .olddotfils in $HOME"
    mkdir $HOME/.olddotfiles
  fi
  if is_not_symlink $HOME/.vimrc; then
    echo "moving old .vimrc to .olddotfiles"
    mv $HOME/.vimrc $HOME/.olddotfiles/.vimrc.old
  fi
  if is_not_symlink $HOME/.zshrc; then
    echo "moving old .zshrc to .olddotfiles"
    mv $HOME/.zshrc $HOME/.olddotfiles/.zshrc.old
  fi
fi

if [ -L $HOME/.vimrc ]; then
  rm $HOME/.vimrc
  echo "linking .vimrc"
  ln -s .dotfiles/vim/.vimrc $HOME/.vimrc
fi

if [ -L $HOME/.zshrc ]; then
  rm $HOME/.zshrc
  echo "linking .zshrc"
  ln -s .dotfiles/zsh/.zshrc $HOME/.zshrc
fi

THEMES="$HOME/.dotfiles/zsh/themes"
SITE_FUNCTIONS=/usr/local/share/zsh/site-functions
if [ ! -L $SITE_FUNCTIONS/prompt_pure_setup ]; then
  echo "linking prompt_pure_setup for pure theme"
  ln -s "$THEMES/pure/pure.zsh" $SITE_FUNCTIONS/prompt_pure_setup
fi

if [ ! -L $SITE_FUNCTIONS/async ]; then
  echo "linking async for pure theme"
  ln -s "$THEMES/pure/async.zsh" $SITE_FUNCTIONS/async
fi
