#!/usr/bin/env zsh

web_search () {
        emulate -L zsh
        typeset -A urls
        urls=(google "https://www.google.com/search?q=" bing "https://www.bing.com/search?q=" yahoo "https://search.yahoo.com/search?p=" duckduckgo "https://www.duckduckgo.com/?q=" startpage "https://www.startpage.com/do/search?q=" yandex "https://yandex.ru/yandsearch?text=" github "https://github.com/search?q=" baidu "https://www.baidu.com/s?wd=" ecosia "https://www.ecosia.org/search?q=" goodreads "https://www.goodreads.com/search?q=" qwant "https://www.qwant.com/?q=" givero "https://www.givero.com/search?q=" stackoverflow "https://stackoverflow.com/search?q=")
        if [[ -z "$urls[$1]" ]]
        then
                echo "Search engine $1 not supported."
                return 1
        fi
        if [[ $# -gt 1 ]]
        then
                url="${urls[$1]}${(j:+:)@[2,-1]}"
        else
                url="${(j://:)${(s:/:)urls[$1]}[1,2]}"
        fi
        open "$url"
}

web_search "$@"
